### PR TITLE
Check dom for element

### PR DESCRIPTION
**Pull request by noahlaux**

### CODE REVIEW

**Comment by TheSharpieOne** [comment]
angular's jQlite's `find()` is "Limited to lookups by tag name"  Also, I am not too sure what this changes is trying to achieve.  
```
    !$document.find(target).length > 0
```

`target` is the element that was clicked on.  This should always be true, as the listener is on the document so it wouldn't trigger for anything that is not in the document.  Unless you are checking to see if the document itself was clicked directly.  I am not too sure how that would happen.

**Comment by noahlaux** [comment]
I'm had a little trouble combining off-click another directive: https://github.com/mbenford/ngTagsInput

It's a classic tag input interface, but what happens is that if you click on items inside the ng-tags-input component, it invokes the `targetInFilter` method, but then `elms[i].contains(target)` returns `false` even though the original `target` was inside an element targeted by `off-click-filter`. I investigated and found out that the ng-tags-input that rendered the element target which was clicked (fx an autocomplete suggestion), had removed the element from DOM, prior to the above expression was invoked.

I know it's an edge case, but what I did here was to make an assumption that if the element target clicked  is not in DOM at all, then it should simply be ignored.

**Comment by noahlaux** [comment]
But you're right, it should not be `find` then, but `querySelector`

**Comment by TheSharpieOne** [comment]
So, with the way the events bubble, the document will get the event last since its the top most element.  This means that the handler in that other directive gets the event and removes the element before the off-client handler.  Chrome has this nice `MouseEvent.path` which provide the DOM tree for the event... but no other browser has it :frowning: 

But I can use `addEventListener` directly (instead of jQlite's `on`) to get access to set `useCapture` to `true` on the listener.  It should pick up the click event first, before that other directive removes the element.  I'll put something up tomorrow.

**Comment by noahlaux** [comment]
that's clever thinking. Awesome.

**Pull request closed without merging**
